## 1. How to import pandas and check the version?

In [1]:
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

1.4.3
{
  "system": {
    "commit": "e8093ba372f9adfe79439d90fe74b0b5b6dea9d6",
    "python": "3.9.13.final.0",
    "python-bits": 64,
    "OS": "Windows",
    "OS-release": "10",
    "Version": "10.0.19044",
    "machine": "AMD64",
    "processor": "Intel64 Family 6 Model 23 Stepping 10, GenuineIntel",
    "byteorder": "little",
    "LC_ALL": null,
    "LANG": null,
    "LOCALE": {
      "language-code": "English_India",
      "encoding": "1252"
    }
  },
  "dependencies": {
    "pandas": "1.4.3",
    "numpy": "1.22.4",
    "pytz": "2022.1",
    "dateutil": "2.8.2",
    "setuptools": "58.1.0",
    "pip": "22.0.4",
    "Cython": null,
    "pytest": null,
    "hypothesis": null,
    "sphinx": null,
    "blosc": null,
    "feather": null,
    "xlsxwriter": null,
    "lxml.etree": "4.9.1",
    "html5lib": null,
    "pymysql": null,
    "psycopg2": null,
    "jinja2": "3.1.2",
    "IPython": "8.4.0",
    "pandas_datareader": null,
    "bs4": "4.11.1",
    "bottleneck": null,
    "brotli":

##  2. How to create a series from a list, numpy array and dict?

In [2]:
# given question 
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
#So to create a series form given data structures we call the function pd.series with parameters as corresponding variables
fromlist = pd.Series(mylist)
fromarr = pd.Series(myarr)
fromdict = pd.Series(mydict)
print(myarr,mydict,mylist)
print('fromarr =',fromarr,'fromdict = ',fromdict,'fromlist',fromlist)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25] {'a': 0, 'b': 1, 'c': 2, 'e': 3, 'd': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25} ['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
fromarr = 0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32 fromdict =  a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32 fromlist 0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h


##  3. How to convert the index of a series into a column of a dataframe?


In [3]:
# Input
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

#soln
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


### to_frame()
to_frame() function is used to convert the given series object to a dataframe. Parameter : name : The passed name should substitute for the series name (if it has one).

### reset_index()
The reset_index() method allows you reset the index back to the default 0, 1, 2 etc indexes. By default this method will keep the "old" idexes in a column named "index", to avoid this, use the drop parameter.

## 4. How to combine many series to form a dataframe? 

In [4]:
#question

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

#soln
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
#     columns : Index or array-like
#     Column labels to use for resulting frame when data does not have them,
#     defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
#     will perform column selection instead.
print(df.head())
#alternate solution
df = pd.concat([ser1, ser2], axis=1)

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


###  pd.concat 
Concatenate pandas objects along a particular axis. Allows optional set logic along the other axes. Can also add a layer of hierarchical indexing on the concatenation axis, which may be useful if the labels are the same (or overlapping) on the passed axis number.

## 5. How to assign name to the series’ index?

In [5]:
#question
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
#answer
ser.name = 'letters'
ser

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: letters, dtype: object

### 6. How to get the items of series A not present in series B?

In [6]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

To explain what we’ve just did:
- the isin method will check, for each index of ser1, if it exists in the RangeIndex of ser2, it will return an ndarray of True and False elements.
- the tilde operator (~) will negate all the elements in the ndarray
- and finally, the df1[ndarray] will return all the rows which correspond to True, in this case if we do something like df1[[False, False, True, True, True]] we get the same result.

### 7. How to get the items not common to both series A and series B?

In [7]:
# Input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Soln
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

##since we are trying to look at the common elements we are doing union and intersection and drop the intresected eelements
#from the union

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

## 8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [8]:
# Input
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

# Solution
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

##  9. How to get frequency counts of unique items of a series?

In [9]:
#question
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser.value_counts()

b    10
c     5
g     4
f     3
a     3
h     2
e     2
d     1
dtype: int64

###  value_counts()

The resulting object will be in descending order so that the
first element is the most frequently-occurring element.
Excludes NA values by default.

## 10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?


In [10]:
#question
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

# Solution
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Nil'
ser

Top 2 Freq: 2    4
3    4
4    3
1    1
dtype: int64


0       2
1       2
2       3
3     Nil
4       3
5     Nil
6       2
7       3
8       3
9     Nil
10      2
11    Nil
dtype: object

### 11. How to bin a numeric series to 10 groups of equal size?

In [11]:
#question
ser = pd.Series(np.random.random(20))
#soln
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()
#qcut does this :
# Quantile-based discretization function.

# Discretize variable into equal-sized buckets based on rank or based
# on sample quantiles. For example 1000 values for 10 quantiles would
# produce a Categorical object indicating quantile membership for each data point.b

0     2nd
1     9th
2    10th
3     1st
4     1st
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

###  12. How to convert a numpy array to a dataframe of given shape? (L1)

In [12]:
ser = pd.Series(np.random.randint(1, 10, 35))
# Solution
df = pd.DataFrame(ser.values.reshape(7,5))
print(df)
   

   0  1  2  3  4
0  9  2  2  6  3
1  6  3  1  6  5
2  2  8  5  8  1
3  3  7  5  7  8
4  3  9  6  2  3
5  4  7  4  9  5
6  6  9  6  5  1


##  13. How to find the positions of numbers that are multiples of 3 from a series?

In [13]:
# Input
ser = pd.Series(np.random.randint(1, 10, 7))
ser
for i in range(len(ser)):
    if ser[i] % 3 == 0:
        print(f'in index =',i ,f'ser[ { i } ]' ,ser[i])
        
#alternate soln in web
print(ser)
#np.argwhere(ser % 3==0)

in index = 2 ser[ 2 ] 9
in index = 3 ser[ 3 ] 9
in index = 4 ser[ 4 ] 3
in index = 5 ser[ 5 ] 3
in index = 6 ser[ 6 ] 3
0    7
1    5
2    9
3    9
4    3
5    3
6    3
dtype: int32


###  argwhere

Find the indices of array elements that are non-zero, grouped by element.

## 14. How to extract items at given positions from a series

In [14]:
#question
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

#soln
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

### ser.take 
Return the elements in the given *positional* indices along an axis.

This means that we are not indexing according to actual values in
the index attribute of the object. We are indexing according to the
actual position of the element in the object.also axis can be given as in put

 ###  15. How to stack two series vertically and horizontally ?

In [15]:
# Input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
ser1.append(ser2)

# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


C:\Users\Msc 1\AppData\Local\Temp\ipykernel_7768\1555075764.py:7: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser1.append(ser2)


###  16. How to get the positions of items of series A in another series B?

In [16]:
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

## 17. How to compute the mean squared error on a truth and predicted series?

In [17]:
# Input
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Solution
np.mean((truth-pred)**2)

0.39719676817642724

### 18. How to convert the first character of each element in a series to uppercase?

In [18]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

#soln
for i in range(len(ser)):
    a = ser[i][0].upper()
    b = ser[i][0]
    #print(a)
    ser[i].replace(b,a)
ser

#other solution
# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

###  19. How to calculate the number of characters in each word in a series?

In [19]:
# Input
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

###  map function ()

Make an iterator that computes the function using arguments from
each of the iterables.  Stops when the shortest iterable is exhausted.
pandas.map() is used to map values from two series having one column same. For mapping two series, the last column of the first series should be same as index column of the second series, also the values should be unique.

### 20. How to compute difference of differences between consequtive numbers of a series?

In [20]:
# Input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

# Solution
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


### Diff()

Python is a great language for doing data analysis, primarily because of the fantastic ecosystem of data-centric python packages. Pandas is one of those packages and makes importing and analyzing data much easier.

Pandas dataframe.diff() is used to find the first discrete difference of objects over the given axis. We can provide a period value to shift for forming the difference.

##  21. How to convert a series of date-strings to a timeseries?


In [21]:
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
ser.map(lambda x: parse(x))

# Solution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

##  dateutil.parser import parse

The parser module can parse datetime strings in many more formats. There can be no better library than dateutil to parse dates and times in Python. To lookup the timezones, the tz module provides everything. When these modules are combined, they make it very easy to parse strings into timezone-aware datetime objects
All it takes is importing the parser module and calling the parse() function with a datetime string. The parser can return a sensible datetime object, but it cannot parse the string, it will raise a ValueError.
How it works :

The parser instead of looking for recognizable tokens, guess what those tokens refer to. It doesn’t use regular expressions.
The order of these tokens matters as it uses a date format that looks like Month/Day/Year (the default order), while others use a Day/Month/Year format.
The parse() function takes an optional keyword argument, dayfirst, which defaults to False to deal with this problem.
It can correctly parse dates in the latter format if it is set to True.

## 22. How to get the day of month, week number, day of year and day of week from a series of date strings?

In [22]:

# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.weekofyear.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())

# day of week
#print("Day of week: ", ser_ts.dt.isocalendar().dayofweek.tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]


C:\Users\Msc 1\AppData\Local\Temp\ipykernel_7768\877829764.py:12: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print("Week number: ", ser_ts.dt.weekofyear.tolist())


## 23. How to filter words that contain atleast 2 vowels from a series?

In [23]:
# Input
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

#  counter() from collections

What is Python Counter?
Python Counter is a container that will hold the count of each of the elements present in the container. The counter is a sub-class available inside the dictionary class.

The counter is a sub-class available inside the dictionary class. Using the Python Counter tool, you can count the key-value pairs in an object, also called a hash table object.

Why use Python Counter?
Here, are major reasons for using Python 3 Counter:

The Counter holds the data in an unordered collection, just like hashtable objects. The elements here represent the keys and the count as values.
It allows you to count the items in an iterable list.
Arithmetic operations like addition, subtraction, intersection, and union can be easily performed on a Counter.
A Counter can also count elements from another counter

Consider you have a following list :

list1 = ['x','y','z','x','x','x','y', 'z']
The list has elements x , y and z.When you use Counter on this list , it will count how many times x , y and z is present. The output if counter is used on list1 should be something like :

Counter({'x': 4, 'y': 2, 'z': 2})
So we have the count of x as 4, y as 2 and z as 2.

Counter with String
In Python, everything is an object and string is an object too. Python string can be created simply by enclosing characters in the double quote. Python does not support a character type. These are treated as strings of length one, also considered as a substring.

In the example below, a string is passed to Counter. It returns dictionary format, with key/value pair where the key is the element and value is the count. It also considers space as an element and gives the count of spaces in the string.


Counter with List
A list is an iterable object that has its elements inside square brackets.

The elements in the list when given to the Counter will be converted to a hashtable objects wherein the elements will become keys and the values will be the count of the elements from the list given.

For example [‘x’,’y’,’z’,’x’,’x’,’x’,’y’,’z’]. Once you give the list the Counter, it will give you the count of each element in the list.


Counter with Dictionary
A dictionary has elements as key/value pair, and they are written inside curly brackets.

Once the dictionary is given to the Counter, it will be converted to a hashtable objects wherein the elements will become keys, and the values will be the count of the elements from the dictionary given.

For example : {‘x’: 4, ‘y’: 2, ‘z’: 2, ‘z’: 2}. The Counter function will try to find the count of each of the key in the given dictionary.

Counter with Tuple
Tuple is a collection of objects separated by commas inside round brackets. Counter will give you the count of each of the elements in the tuple given.

Once the tuple is given to the Counter, it will be converted to a hashtable object wherein the elements will become keys and the values will be the count of the elements from the tuple given.

from collections import Counter
tuple1 = ('x','y','z','x','x','x','y','z')
print(Counter(tuple1))
Output:

Counter({'x': 4, 'y': 2, 'z': 2})

## 24.How to get the mean of a series grouped by another series?

In [24]:
# Input
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# Solution
weights.groupby(fruit).mean()

banana    5.000000
carrot    6.666667
dtype: float64

## 25. How to compute the euclidean distance between two series?

In [25]:
# Input
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Solution (using func)
np.linalg.norm(p-q)

# alternate from net Solution 
sum((p - q)**2)**.5


18.16590212458495

## 26. How to find all the local maxima (or peaks) in a numeric series?

In [26]:
# Input
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Solution
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int64)

## 27. How to replace missing spaces in a string with the least frequent character?

In [27]:
# Input
my_str = 'dbc deb abed gade'

# Solution
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
b    3
     3
e    3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

## 28. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

In [28]:
# Input
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

# Alternatives
ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

## 29. How to compute the autocorrelations of a numeric series?

In [29]:
# Input
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[-0.49, 0.49, -0.42, 0.64, -0.58, 0.55, -0.56, 0.56, -0.66, 0.61]
Lag having highest correlation:  9


## autocorr(i)
Compute the lag-N autocorrelation.
This method computes the Pearson correlation between
the Series and its shifted self.

Parameters
----------
lag : int, default 1
    Number of lags to apply before performing autocorrelation.

Returns
-------
float
    The Pearson correlation between self and self.shift(lag).

## 30. How to create a dataframe with rows as strides from a given series?

In [30]:
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

## 31. How to check if a dataframe has any missing values?

In [31]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df.isnull().values.any()

True

### isnull()
Detect missing values.

Return a boolean same-sized object indicating if the values are NA.
NA values, such as None or :attr:`numpy.NaN`, gets mapped to True
values.
Everything else gets mapped to False values. Characters such as empty
strings ``''`` or :attr:`numpy.inf` are not considered NA values
(unless you set ``pandas.options.mode.use_inf_as_na = True``).

Returns
-------
DataFrame
    Mask of bool values for each element in DataFrame that
    indicates whether an element is an NA value.

## 32. How to count the number of missing values in each column?

In [32]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

## 33. How to use apply function on existing columns with global variables as additional arguments?

In [33]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df.head(5)

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9      18.80      25.0   
1          NaN   Legend  Midsize  29.200000   33.9      38.70      18.0   
2         Audi       90  Compact  25.900000   29.1      32.30      20.0   
3         Audi      100  Midsize  17.118605   37.7      44.60      19.0   
4          BMW     535i  Midsize  17.118605   30.0      19.15      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

## The args argument given to apply function is passed func argument (lambda function given). You are getting this error since two arguments are given but lambda function only accepts one argument.

## 34.How to select a specific column from a dataframe as a dataframe instead of a series?

In [34]:
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

# Alternately the following returns a Series
type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])

pandas.core.series.Series

## 35.How to change the order of columns of a dataframe?

In [35]:
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
print(df)
# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)

df

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

## 36.How to set the number of rows and columns displayed in the output?

In [36]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df



Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

## 37. How to format all the values in a dataframe as percentages?

In [37]:
# Input
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Solution
out = df.style.format({
    'random': '{0:.2%}'.format,
})


## style()
Returns a Styler object.

Contains methods for building a styled HTML representation of the DataFrame.

more
-------
io.formats.style.Styler : Helps style a DataFrame or Series according to the
    data with HTML and CSS.
    
  
  ### df.style.format(
    formatter: 'ExtFormatter | None' = None,
    subset: 'Subset | None' = None,
    na_rep: 'str | None' = None,
    precision: 'int | None' = None,
    decimal: 'str' = '.',
    thousands: 'str | None' = None,
    escape: 'str | None' = None,
    hyperlinks: 'str | None' = None,
) -> 'StylerRenderer'
Docstring:
Format the text display value of cells.

Parameters
----------
formatter : str, callable, dict or None
    Object to define how values are displayed. See notes.
subset : label, array-like, IndexSlice, optional
    A valid 2d input to `DataFrame.loc[<subset>]`, or, in the case of a 1d input
    or single key, to `DataFrame.loc[:, <subset>]` where the columns are
    prioritised, to limit ``data`` to *before* applying the function.
na_rep : str, optional
    Representation for missing values.
    If ``na_rep`` is None, no special formatting is applied.

## 38.  How to create a primary key index by combining relevant columns?

In [38]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

# Solution
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


## 39. How to get the row number of the nth largest value in a column?

In [39]:
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Solution
n = 5
df['a'].argsort()[::-1][n]

0

## argsort()
argsort() function is used to perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as arr that would sort the array. It means indices of value arranged in ascending order

Syntax : numpy.argsort(arr, axis=-1, kind=’quicksort’, order=None) 

Parameters:

arr : [array_like] Input array. 
axis : [int or None] Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis. 
kind : [‘quicksort’, ‘mergesort’, ‘heapsort’]Selection algorithm. Default is ‘quicksort’. 
order : [str or list of str] When arr is an array with fields defined, this argument specifies which fields to compare first, second, etc. 
Return: [index_array, ndarray] Array of indices that sort arr along the specified axis.If arr is one-dimensional then arr[index_array] returns a sorted arr.

## 40. How to find the position of the nth largest value greater than a given value?

In [40]:
# Input
ser = pd.Series(np.random.randint(1, 100, 15))

# Solution
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))


ser:  [84, 24, 78, 10, 25, 94, 37, 92, 94, 50, 91, 36, 79, 86, 49] mean:  62


## 41.How to get the last n rows of a dataframe with row sum > 100?

In [41]:
# Input
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Solution
# print row sums
rowsums = df.apply(np.sum, axis=1)

# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
last_two_rows

0   1   2   3
6   25  13  36  31
12  38  18  24  36

##  42. How to reshape a dataframe to the largest possible square after removing the negative values?

In [42]:
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  20  30  47  37  -6  17  39  34  30  47
1  -7  -7  10  -8  46  15 -10  42  25   4
2  -2 -17 -19  29  -2  25  24   3  19  21
3  12   7 -10  -7  18  -5  36  41 -12 -14
4   7  44 -14  -6  14  45  26  34 -11 -18
5  34 -19  14  34  36  35   8  16   1   2
6  -9  18 -15  48  37  21   8  45  24  46
7   2 -12  44  42  46  26   6 -16  16   1
8  20 -10  15  35  -8   8 -10  39  11  21
9 -19  26  33 -17  33 -12  23   1  35 -10
[[20. 30. 47. 37. 17. 39. 34. 30.]
 [47. 10. 46. 15. 42. 25.  4. 29.]
 [25. 24. 19. 21. 12.  7. 18. 36.]
 [41.  7. 44. 14. 45. 26. 34. 34.]
 [14. 34. 36. 35.  8. 16. 18. 48.]
 [37. 21.  8. 45. 24. 46. 44. 42.]
 [46. 26.  6. 16. 20. 15. 35.  8.]
 [39. 11. 21. 26. 33. 33. 23. 35.]]


## 43.How to swap two rows of a dataframe?

In [43]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
# Solution
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print('after swpping: \n',swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
after swpping: 
     0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


## 44.How to reverse the rows of a dataframe?

In [44]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
# Solution 1
df.iloc[::-1, :]
print("after swapping")
# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
after swapping
    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


## 45. Which column contains the highest number of row-wise maximum values?

In [45]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

# Solution
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  0


## 46.How to create a new column that contains the row number of nearest column by euclidean distance?

In [46]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

# Solution
import numpy as np

# initial outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s nearest_row  dist
a  22  35  31   3           h   104
b  74   4  26  62           f    99
c  82  32  51   7           h   111
d  91  21  12  76           f   114
e  53  25  59  58           a    70
f  17  62  77  36           d   114
g  25  63  34  44           d    87
h  25  64  70  95           c   111
i  92  70  64  63           j   107
j   2  31  23  78           c   111

## 47.How to create a column containing the minimum by maximum of each row?

In [47]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution 1
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

# Solution 2
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)
min_by_max

0    0.180851
1    0.081633
2    0.100000
3    0.438202
4    0.408163
5    0.010309
6    0.030612
7    0.011765
dtype: float64

## 48. How to normalize all columns in a dataframe?

In [48]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0 -0.80 -0.64  0.59 -0.60  0.87 -0.05 -1.26 -1.65 -1.14  0.75
1 -1.19  1.27 -0.51 -1.95  0.64  0.42  1.07  1.00  0.98 -1.39
2 -0.85 -0.75  0.44  0.45 -1.67  1.03  1.07 -0.84  0.26 -1.11
3 -0.71  1.58  2.02  0.62 -0.40 -1.09 -1.05  0.24  0.73  0.58
4  1.01 -0.05 -0.03 -0.65  1.01  0.42  0.77 -0.02  0.55  0.53
5  0.92  0.45 -0.87  1.02 -0.12 -0.73 -1.00  1.41 -1.21  0.87
6  0.30 -1.03 -0.69  0.86 -1.11 -1.38  0.61 -0.58  1.01 -1.08
7  1.32 -0.81 -0.95  0.25  0.78  1.39 -0.22  0.44 -1.17  0.87
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.84  0.85  0.48  0.55  0.05  0.52  1.00  1.00  0.97  0.05
1  1.00  0.12  0.85  1.00  0.14  0.35  0.00  0.13  0.02  1.00
2  0.87  0.89  0.53  0.19  1.00  0.13  0.00  0.73  0.34  0.87
3  0.81  0.00  0.00  0.14  0.53  0.90  0.91  0.38  0.13  0.13
4  0.12  0.62  0.69  0.56  0.00  0.35  0.13  0.47  0.21  0.15
5  0.16  0.43  0.98  0.00  0.42  0.77  0.89 

## 49.How to replace both the diagonals of dataframe with 0?

In [49]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

### iat()
Access a single value for a row/column pair by integer position.

Similar to ``iloc``, in that both provide integer-based lookups. Use
``iat`` if you only need to get or set a single value in a DataFrame
or Series.
Examples
--------
>>> df = pd.DataFrame([[0, 2, 3], [0, 4, 1], [10, 20, 30]],
...                   columns=['A', 'B', 'C'])
>>> df
    A   B   C
0   0   2   3
1   0   4   1
2  10  20  30

Get value at specified row/column pair

>>> df.iat[1, 2]
1

Set value at specified row/column pair

>>> df.iat[1, 2] = 10
>>> df.iat[1, 2]
10

Get value within a series

>>> df.loc[0].iat[1]
2

## 50.How to join two dataframes by 2 columns so they have only the common rows?

In [53]:
# Input
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

# Soln
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

fruit weight  price_left  pazham  kilo  price_right
0   apple   high          10   apple  high            3
1   apple   high          12   apple  high            3
2   apple   high          11   apple  high            3
3  orange    low           5  orange   low            5
4  orange    low           5  orange   low            5
5  orange    low           2  orange   low            5

## merge()
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'str' = 'inner',
    on: 'IndexLabel | None' = None,
    left_on: 'IndexLabel | None' = None,
    right_on: 'IndexLabel | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool' = True,
    indicator: 'bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.

      .. versionadded:: 1.2.0

on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.